import { AxiosRequestConfig } from 'axios';
import { InjectedProps } from 'react-typestyle-preset';
import { InputSheet } from 'react-typestyle';

import { ComponentType, ReactNode } from 'react';

export enum DragItem {
    PIECE = 'UIPiece'
}

export const DragItems = [ DragItem.PIECE ]

declare module 'react' {

    type Provider<T> = ComponentType<{
        value: T;
        children?: ReactNode;
    }>;
    type Consumer<T> = ComponentType<{
        children: (value: T) => ReactNode;
        unstable_observedBits?: number;
    }>;

    interface Context<T> {
        Provider: Provider<T>;
        Consumer: Consumer<T>;
    }

    function createContext<T>(defaultValue?: T, calculateChangedBits?: (prev: T, next: T) => number): Context<T>;


    type RefObject<T> = {
        value: T | null
    };

    export function createRef()

}



export type GameMode = 'free' | 'singleplayer' | 'multiplayer'

export interface ApiCacheConfig {
    enabled?: boolean
    expires?: number | null
    useETag?: boolean
}

export interface ApiDebugConfig {
    limiter?: false | number
}

export interface ApiRequestConfig extends AxiosRequestConfig {
    useCache?: boolean
    cache?: ApiCacheConfig
    debug?: ApiDebugConfig
}

export interface BreakpointDictionary<T> {
    xs: T
    sm: T
    md: T
    lg: T
    xl: T
    xxl: T
}

export type Breakpoint = keyof BreakpointDictionary<any>

export type StyleProps = Partial<InjectedProps>
export type ClassStyles<T> = InputSheet<T>

export type FontAwesomeIcon = keyof FontAwesomeIcons
export type FontAwesomePrefixedIcon = keyof FontAwesomePrefixedIcons

export interface FontAwesomeIcons {
    '500px': string
    'adjust': string
    'adn': string
    'align-center': string
    'align-justify': string
    'align-left': string
    'align-right': string
    'amazon': string
    'ambulance': string
    'anchor': string
    'android': string
    'angellist': string
    'angle-double-down': string
    'angle-double-left': string
    'angle-double-right': string
    'angle-double-up': string
    'angle-down': string
    'angle-left': string
    'angle-right': string
    'angle-up': string
    'apple': string
    'archive': string
    'area-chart': string
    'arrow-circle-down': string
    'arrow-circle-left': string
    'arrow-circle-o-down': string
    'arrow-circle-o-left': string
    'arrow-circle-o-right': string
    'arrow-circle-o-up': string
    'arrow-circle-right': string
    'arrow-circle-up': string
    'arrow-down': string
    'arrow-left': string
    'arrow-right': string
    'arrow-up': string
    'arrows': string
    'arrows-alt': string
    'arrows-h': string
    'arrows-v': string
    'asterisk': string
    'at': string
    'automobile': string
    'backward': string
    'balance-scale': string
    'ban': string
    'bank': string
    'bar-chart': string
    'bar-chart-o': string
    'barcode': string
    'bars': string
    'battery-0': string
    'battery-1': string
    'battery-2': string
    'battery-3': string
    'battery-4': string
    'battery-empty': string
    'battery-full': string
    'battery-half': string
    'battery-quarter': string
    'battery-three-quarters': string
    'bed': string
    'beer': string
    'behance': string
    'behance-square': string
    'bell': string
    'bell-o': string
    'bell-slash': string
    'bell-slash-o': string
    'bicycle': string
    'binoculars': string
    'birthday-cake': string
    'bitbucket': string
    'bitbucket-square': string
    'bitcoin': string
    'black-tie': string
    'bluetooth': string
    'bluetooth-b': string
    'bold': string
    'bolt': string
    'bomb': string
    'book': string
    'bookmark': string
    'bookmark-o': string
    'briefcase': string
    'btc': string
    'bug': string
    'building': string
    'building-o': string
    'bullhorn': string
    'bullseye': string
    'bus': string
    'buysellads': string
    'cab': string
    'calculator': string
    'calendar': string
    'calendar-check-o': string
    'calendar-minus-o': string
    'calendar-o': string
    'calendar-plus-o': string
    'calendar-times-o': string
    'camera': string
    'camera-retro': string
    'car': string
    'caret-down': string
    'caret-left': string
    'caret-right': string
    'caret-square-o-down': string
    'caret-square-o-left': string
    'caret-square-o-right': string
    'caret-square-o-up': string
    'caret-up': string
    'cart-arrow-down': string
    'cart-plus': string
    'cc': string
    'cc-amex': string
    'cc-diners-club': string
    'cc-discover': string
    'cc-jcb': string
    'cc-mastercard': string
    'cc-paypal': string
    'cc-stripe': string
    'cc-visa': string
    'certificate': string
    'chain': string
    'chain-broken': string
    'check': string
    'check-circle': string
    'check-circle-o': string
    'check-square': string
    'check-square-o': string
    'chevron-circle-down': string
    'chevron-circle-left': string
    'chevron-circle-right': string
    'chevron-circle-up': string
    'chevron-down': string
    'chevron-left': string
    'chevron-right': string
    'chevron-up': string
    'child': string
    'chrome': string
    'circle': string
    'circle-o': string
    'circle-o-notch': string
    'circle-thin': string
    'clipboard': string
    'clock-o': string
    'clone': string
    'close': string
    'cloud': string
    'cloud-download': string
    'cloud-upload': string
    'cny': string
    'code': string
    'code-fork': string
    'codepen': string
    'codiepie': string
    'coffee': string
    'cog': string
    'cogs': string
    'columns': string
    'comment': string
    'comment-o': string
    'commenting': string
    'commenting-o': string
    'comments': string
    'comments-o': string
    'compass': string
    'compress': string
    'connectdevelop': string
    'contao': string
    'copy': string
    'copyright': string
    'creative-commons': string
    'credit-card': string
    'credit-card-alt': string
    'crop': string
    'crosshairs': string
    'css3': string
    'cube': string
    'cubes': string
    'cut': string
    'cutlery': string
    'dashboard': string
    'dashcube': string
    'database': string
    'dedent': string
    'delicious': string
    'desktop': string
    'deviantart': string
    'diamond': string
    'digg': string
    'dollar': string
    'dot-circle-o': string
    'download': string
    'dribbble': string
    'dropbox': string
    'drupal': string
    'edge': string
    'edit': string
    'eject': string
    'ellipsis-h': string
    'ellipsis-v': string
    'empire': string
    'envelope': string
    'envelope-o': string
    'envelope-square': string
    'eraser': string
    'eur': string
    'euro': string
    'exchange': string
    'exclamation': string
    'exclamation-circle': string
    'exclamation-triangle': string
    'expand': string
    'expeditedssl': string
    'external-link': string
    'external-link-square': string
    'eye': string
    'eye-slash': string
    'eyedropper': string
    'facebook': string
    'facebook-f': string
    'facebook-official': string
    'facebook-square': string
    'fast-backward': string
    'fast-forward': string
    'fax': string
    'feed': string
    'female': string
    'fighter-jet': string
    'file': string
    'file-archive-o': string
    'file-audio-o': string
    'file-code-o': string
    'file-excel-o': string
    'file-image-o': string
    'file-movie-o': string
    'file-o': string
    'file-pdf-o': string
    'file-photo-o': string
    'file-picture-o': string
    'file-powerpoint-o': string
    'file-sound-o': string
    'file-text': string
    'file-text-o': string
    'file-video-o': string
    'file-word-o': string
    'file-zip-o': string
    'files-o': string
    'film': string
    'filter': string
    'fire': string
    'fire-extinguisher': string
    'firefox': string
    'flag': string
    'flag-checkered': string
    'flag-o': string
    'flash': string
    'flask': string
    'flickr': string
    'floppy-o': string
    'folder': string
    'folder-o': string
    'folder-open': string
    'folder-open-o': string
    'font': string
    'fonticons': string
    'fort-awesome': string
    'forumbee': string
    'forward': string
    'foursquare': string
    'frown-o': string
    'futbol-o': string
    'gamepad': string
    'gavel': string
    'gbp': string
    'ge': string
    'gear': string
    'gears': string
    'genderless': string
    'get-pocket': string
    'gg': string
    'gg-circle': string
    'gift': string
    'git': string
    'git-square': string
    'github': string
    'github-alt': string
    'github-square': string
    'gittip': string
    'glass': string
    'globe': string
    'google': string
    'google-plus': string
    'google-plus-square': string
    'google-wallet': string
    'graduation-cap': string
    'gratipay': string
    'group': string
    'h-square': string
    'hacker-news': string
    'hand-grab-o': string
    'hand-lizard-o': string
    'hand-o-down': string
    'hand-o-left': string
    'hand-o-right': string
    'hand-o-up': string
    'hand-paper-o': string
    'hand-peace-o': string
    'hand-pointer-o': string
    'hand-rock-o': string
    'hand-scissors-o': string
    'hand-spock-o': string
    'hand-stop-o': string
    'hashtag': string
    'hdd-o': string
    'header': string
    'headphones': string
    'heart': string
    'heart-o': string
    'heartbeat': string
    'history': string
    'home': string
    'hospital-o': string
    'hotel': string
    'hourglass': string
    'hourglass-1': string
    'hourglass-2': string
    'hourglass-3': string
    'hourglass-end': string
    'hourglass-half': string
    'hourglass-o': string
    'hourglass-start': string
    'houzz': string
    'html5': string
    'i-cursor': string
    'ils': string
    'image': string
    'inbox': string
    'indent': string
    'industry': string
    'info': string
    'info-circle': string
    'inr': string
    'instagram': string
    'institution': string
    'internet-explorer': string
    'intersex': string
    'ioxhost': string
    'italic': string
    'joomla': string
    'jpy': string
    'jsfiddle': string
    'key': string
    'keyboard-o': string
    'krw': string
    'language': string
    'laptop': string
    'lastfm': string
    'lastfm-square': string
    'leaf': string
    'leanpub': string
    'legal': string
    'lemon-o': string
    'level-down': string
    'level-up': string
    'life-bouy': string
    'life-buoy': string
    'life-ring': string
    'life-saver': string
    'lightbulb-o': string
    'line-chart': string
    'link': string
    'linkedin': string
    'linkedin-square': string
    'linux': string
    'list': string
    'list-alt': string
    'list-ol': string
    'list-ul': string
    'location-arrow': string
    'lock': string
    'long-arrow-down': string
    'long-arrow-left': string
    'long-arrow-right': string
    'long-arrow-up': string
    'magic': string
    'magnet': string
    'mail-forward': string
    'mail-reply': string
    'mail-reply-all': string
    'male': string
    'map': string
    'map-marker': string
    'map-o': string
    'map-pin': string
    'map-signs': string
    'mars': string
    'mars-double': string
    'mars-stroke': string
    'mars-stroke-h': string
    'mars-stroke-v': string
    'maxcdn': string
    'meanpath': string
    'medium': string
    'medkit': string
    'meh-o': string
    'mercury': string
    'microphone': string
    'microphone-slash': string
    'minus': string
    'minus-circle': string
    'minus-square': string
    'minus-square-o': string
    'mixcloud': string
    'mobile': string
    'mobile-phone': string
    'modx': string
    'money': string
    'moon-o': string
    'mortar-board': string
    'motorcycle': string
    'mouse-pointer': string
    'music': string
    'navicon': string
    'neuter': string
    'newspaper-o': string
    'object-group': string
    'object-ungroup': string
    'odnoklassniki': string
    'odnoklassniki-square': string
    'opencart': string
    'openid': string
    'opera': string
    'optin-monster': string
    'outdent': string
    'pagelines': string
    'paint-brush': string
    'paper-plane': string
    'paper-plane-o': string
    'paperclip': string
    'paragraph': string
    'paste': string
    'pause': string
    'pause-circle': string
    'pause-circle-o': string
    'paw': string
    'paypal': string
    'pencil': string
    'pencil-square': string
    'pencil-square-o': string
    'percent': string
    'phone': string
    'phone-square': string
    'photo': string
    'picture-o': string
    'pie-chart': string
    'pied-piper': string
    'pied-piper-alt': string
    'pinterest': string
    'pinterest-p': string
    'pinterest-square': string
    'plane': string
    'play': string
    'play-circle': string
    'play-circle-o': string
    'plug': string
    'plus': string
    'plus-circle': string
    'plus-square': string
    'plus-square-o': string
    'power-off': string
    'print': string
    'product-hunt': string
    'puzzle-piece': string
    'qq': string
    'qrcode': string
    'question': string
    'question-circle': string
    'quote-left': string
    'quote-right': string
    'ra': string
    'random': string
    'rebel': string
    'recycle': string
    'reddit': string
    'reddit-alien': string
    'reddit-square': string
    'refresh': string
    'registered': string
    'remove': string
    'renren': string
    'reorder': string
    'repeat': string
    'reply': string
    'reply-all': string
    'retweet': string
    'rmb': string
    'road': string
    'rocket': string
    'rotate-left': string
    'rotate-right': string
    'rouble': string
    'rss': string
    'rss-square': string
    'rub': string
    'ruble': string
    'rupee': string
    'safari': string
    'save': string
    'scissors': string
    'scribd': string
    'search': string
    'search-minus': string
    'search-plus': string
    'sellsy': string
    'send': string
    'send-o': string
    'server': string
    'share': string
    'share-alt': string
    'share-alt-square': string
    'share-square': string
    'share-square-o': string
    'shekel': string
    'sheqel': string
    'shield': string
    'ship': string
    'shirtsinbulk': string
    'shopping-bag': string
    'shopping-basket': string
    'shopping-cart': string
    'sign-in': string
    'sign-out': string
    'signal': string
    'simplybuilt': string
    'sitemap': string
    'skyatlas': string
    'skype': string
    'slack': string
    'sliders': string
    'slideshare': string
    'smile-o': string
    'soccer-ball-o': string
    'sort': string
    'sort-alpha-asc': string
    'sort-alpha-desc': string
    'sort-amount-asc': string
    'sort-amount-desc': string
    'sort-asc': string
    'sort-desc': string
    'sort-down': string
    'sort-numeric-asc': string
    'sort-numeric-desc': string
    'sort-up': string
    'soundcloud': string
    'space-shuttle': string
    'spinner': string
    'spoon': string
    'spotify': string
    'square': string
    'square-o': string
    'stack-exchange': string
    'stack-overflow': string
    'star': string
    'star-half': string
    'star-half-empty': string
    'star-half-full': string
    'star-half-o': string
    'star-o': string
    'steam': string
    'steam-square': string
    'step-backward': string
    'step-forward': string
    'stethoscope': string
    'sticky-note': string
    'sticky-note-o': string
    'stop': string
    'stop-circle': string
    'stop-circle-o': string
    'street-view': string
    'strikethrough': string
    'stumbleupon': string
    'stumbleupon-circle': string
    'subscript': string
    'subway': string
    'suitcase': string
    'sun-o': string
    'superscript': string
    'support': string
    'table': string
    'tablet': string
    'tachometer': string
    'tag': string
    'tags': string
    'tasks': string
    'taxi': string
    'television': string
    'tencent-weibo': string
    'terminal': string
    'text-height': string
    'text-width': string
    'th': string
    'th-large': string
    'th-list': string
    'thumb-tack': string
    'thumbs-down': string
    'thumbs-o-down': string
    'thumbs-o-up': string
    'thumbs-up': string
    'ticket': string
    'times': string
    'times-circle': string
    'times-circle-o': string
    'tint': string
    'toggle-down': string
    'toggle-left': string
    'toggle-off': string
    'toggle-on': string
    'toggle-right': string
    'toggle-up': string
    'trademark': string
    'train': string
    'transgender': string
    'transgender-alt': string
    'trash': string
    'trash-o': string
    'tree': string
    'trello': string
    'tripadvisor': string
    'trophy': string
    'truck': string
    'try': string
    'tty': string
    'tumblr': string
    'tumblr-square': string
    'turkish-lira': string
    'tv': string
    'twitch': string
    'twitter': string
    'twitter-square': string
    'umbrella': string
    'underline': string
    'undo': string
    'university': string
    'unlink': string
    'unlock': string
    'unlock-alt': string
    'unsorted': string
    'upload': string
    'usb': string
    'usd': string
    'user': string
    'user-md': string
    'user-plus': string
    'user-secret': string
    'user-times': string
    'users': string
    'venus': string
    'venus-double': string
    'venus-mars': string
    'viacoin': string
    'video-camera': string
    'vimeo': string
    'vimeo-square': string
    'vine': string
    'vk': string
    'volume-down': string
    'volume-off': string
    'volume-up': string
    'warning': string
    'wechat': string
    'weibo': string
    'weixin': string
    'whatsapp': string
    'wheelchair': string
    'wifi': string
    'wikipedia-w': string
    'windows': string
    'won': string
    'wordpress': string
    'wrench': string
    'xing': string
    'xing-square': string
    'y-combinator': string
    'y-combinator-square': string
    'yahoo': string
    'yc': string
    'yc-square': string
    'yelp': string
    'yen': string
    'youtube': string
    'youtube-play': string
    'youtube-square': string
}

export interface FontAwesomePrefixedIcons {
    'fa-500px': string
    'fa-adjust': string
    'fa-adn': string
    'fa-align-center': string
    'fa-align-justify': string
    'fa-align-left': string
    'fa-align-right': string
    'fa-amazon': string
    'fa-ambulance': string
    'fa-anchor': string
    'fa-android': string
    'fa-angellist': string
    'fa-angle-double-down': string
    'fa-angle-double-left': string
    'fa-angle-double-right': string
    'fa-angle-double-up': string
    'fa-angle-down': string
    'fa-angle-left': string
    'fa-angle-right': string
    'fa-angle-up': string
    'fa-apple': string
    'fa-archive': string
    'fa-area-chart': string
    'fa-arrow-circle-down': string
    'fa-arrow-circle-left': string
    'fa-arrow-circle-o-down': string
    'fa-arrow-circle-o-left': string
    'fa-arrow-circle-o-right': string
    'fa-arrow-circle-o-up': string
    'fa-arrow-circle-right': string
    'fa-arrow-circle-up': string
    'fa-arrow-down': string
    'fa-arrow-left': string
    'fa-arrow-right': string
    'fa-arrow-up': string
    'fa-arrows': string
    'fa-arrows-alt': string
    'fa-arrows-h': string
    'fa-arrows-v': string
    'fa-asterisk': string
    'fa-at': string
    'fa-automobile': string
    'fa-backward': string
    'fa-balance-scale': string
    'fa-ban': string
    'fa-bank': string
    'fa-bar-chart': string
    'fa-bar-chart-o': string
    'fa-barcode': string
    'fa-bars': string
    'fa-battery-0': string
    'fa-battery-1': string
    'fa-battery-2': string
    'fa-battery-3': string
    'fa-battery-4': string
    'fa-battery-empty': string
    'fa-battery-full': string
    'fa-battery-half': string
    'fa-battery-quarter': string
    'fa-battery-three-quarters': string
    'fa-bed': string
    'fa-beer': string
    'fa-behance': string
    'fa-behance-square': string
    'fa-bell': string
    'fa-bell-o': string
    'fa-bell-slash': string
    'fa-bell-slash-o': string
    'fa-bicycle': string
    'fa-binoculars': string
    'fa-birthday-cake': string
    'fa-bitbucket': string
    'fa-bitbucket-square': string
    'fa-bitcoin': string
    'fa-black-tie': string
    'fa-bluetooth': string
    'fa-bluetooth-b': string
    'fa-bold': string
    'fa-bolt': string
    'fa-bomb': string
    'fa-book': string
    'fa-bookmark': string
    'fa-bookmark-o': string
    'fa-briefcase': string
    'fa-btc': string
    'fa-bug': string
    'fa-building': string
    'fa-building-o': string
    'fa-bullhorn': string
    'fa-bullseye': string
    'fa-bus': string
    'fa-buysellads': string
    'fa-cab': string
    'fa-calculator': string
    'fa-calendar': string
    'fa-calendar-check-o': string
    'fa-calendar-minus-o': string
    'fa-calendar-o': string
    'fa-calendar-plus-o': string
    'fa-calendar-times-o': string
    'fa-camera': string
    'fa-camera-retro': string
    'fa-car': string
    'fa-caret-down': string
    'fa-caret-left': string
    'fa-caret-right': string
    'fa-caret-square-o-down': string
    'fa-caret-square-o-left': string
    'fa-caret-square-o-right': string
    'fa-caret-square-o-up': string
    'fa-caret-up': string
    'fa-cart-arrow-down': string
    'fa-cart-plus': string
    'fa-cc': string
    'fa-cc-amex': string
    'fa-cc-diners-club': string
    'fa-cc-discover': string
    'fa-cc-jcb': string
    'fa-cc-mastercard': string
    'fa-cc-paypal': string
    'fa-cc-stripe': string
    'fa-cc-visa': string
    'fa-certificate': string
    'fa-chain': string
    'fa-chain-broken': string
    'fa-check': string
    'fa-check-circle': string
    'fa-check-circle-o': string
    'fa-check-square': string
    'fa-check-square-o': string
    'fa-chevron-circle-down': string
    'fa-chevron-circle-left': string
    'fa-chevron-circle-right': string
    'fa-chevron-circle-up': string
    'fa-chevron-down': string
    'fa-chevron-left': string
    'fa-chevron-right': string
    'fa-chevron-up': string
    'fa-child': string
    'fa-chrome': string
    'fa-circle': string
    'fa-circle-o': string
    'fa-circle-o-notch': string
    'fa-circle-thin': string
    'fa-clipboard': string
    'fa-clock-o': string
    'fa-clone': string
    'fa-close': string
    'fa-cloud': string
    'fa-cloud-download': string
    'fa-cloud-upload': string
    'fa-cny': string
    'fa-code': string
    'fa-code-fork': string
    'fa-codepen': string
    'fa-codiepie': string
    'fa-coffee': string
    'fa-cog': string
    'fa-cogs': string
    'fa-columns': string
    'fa-comment': string
    'fa-comment-o': string
    'fa-commenting': string
    'fa-commenting-o': string
    'fa-comments': string
    'fa-comments-o': string
    'fa-compass': string
    'fa-compress': string
    'fa-connectdevelop': string
    'fa-contao': string
    'fa-copy': string
    'fa-copyright': string
    'fa-creative-commons': string
    'fa-credit-card': string
    'fa-credit-card-alt': string
    'fa-crop': string
    'fa-crosshairs': string
    'fa-css3': string
    'fa-cube': string
    'fa-cubes': string
    'fa-cut': string
    'fa-cutlery': string
    'fa-dashboard': string
    'fa-dashcube': string
    'fa-database': string
    'fa-dedent': string
    'fa-delicious': string
    'fa-desktop': string
    'fa-deviantart': string
    'fa-diamond': string
    'fa-digg': string
    'fa-dollar': string
    'fa-dot-circle-o': string
    'fa-download': string
    'fa-dribbble': string
    'fa-dropbox': string
    'fa-drupal': string
    'fa-edge': string
    'fa-edit': string
    'fa-eject': string
    'fa-ellipsis-h': string
    'fa-ellipsis-v': string
    'fa-empire': string
    'fa-envelope': string
    'fa-envelope-o': string
    'fa-envelope-square': string
    'fa-eraser': string
    'fa-eur': string
    'fa-euro': string
    'fa-exchange': string
    'fa-exclamation': string
    'fa-exclamation-circle': string
    'fa-exclamation-triangle': string
    'fa-expand': string
    'fa-expeditedssl': string
    'fa-external-link': string
    'fa-external-link-square': string
    'fa-eye': string
    'fa-eye-slash': string
    'fa-eyedropper': string
    'fa-facebook': string
    'fa-facebook-f': string
    'fa-facebook-official': string
    'fa-facebook-square': string
    'fa-fast-backward': string
    'fa-fast-forward': string
    'fa-fax': string
    'fa-feed': string
    'fa-female': string
    'fa-fighter-jet': string
    'fa-file': string
    'fa-file-archive-o': string
    'fa-file-audio-o': string
    'fa-file-code-o': string
    'fa-file-excel-o': string
    'fa-file-image-o': string
    'fa-file-movie-o': string
    'fa-file-o': string
    'fa-file-pdf-o': string
    'fa-file-photo-o': string
    'fa-file-picture-o': string
    'fa-file-powerpoint-o': string
    'fa-file-sound-o': string
    'fa-file-text': string
    'fa-file-text-o': string
    'fa-file-video-o': string
    'fa-file-word-o': string
    'fa-file-zip-o': string
    'fa-files-o': string
    'fa-film': string
    'fa-filter': string
    'fa-fire': string
    'fa-fire-extinguisher': string
    'fa-firefox': string
    'fa-flag': string
    'fa-flag-checkered': string
    'fa-flag-o': string
    'fa-flash': string
    'fa-flask': string
    'fa-flickr': string
    'fa-floppy-o': string
    'fa-folder': string
    'fa-folder-o': string
    'fa-folder-open': string
    'fa-folder-open-o': string
    'fa-font': string
    'fa-fonticons': string
    'fa-fort-awesome': string
    'fa-forumbee': string
    'fa-forward': string
    'fa-foursquare': string
    'fa-frown-o': string
    'fa-futbol-o': string
    'fa-gamepad': string
    'fa-gavel': string
    'fa-gbp': string
    'fa-ge': string
    'fa-gear': string
    'fa-gears': string
    'fa-genderless': string
    'fa-get-pocket': string
    'fa-gg': string
    'fa-gg-circle': string
    'fa-gift': string
    'fa-git': string
    'fa-git-square': string
    'fa-github': string
    'fa-github-alt': string
    'fa-github-square': string
    'fa-gittip': string
    'fa-glass': string
    'fa-globe': string
    'fa-google': string
    'fa-google-plus': string
    'fa-google-plus-square': string
    'fa-google-wallet': string
    'fa-graduation-cap': string
    'fa-gratipay': string
    'fa-group': string
    'fa-h-square': string
    'fa-hacker-news': string
    'fa-hand-grab-o': string
    'fa-hand-lizard-o': string
    'fa-hand-o-down': string
    'fa-hand-o-left': string
    'fa-hand-o-right': string
    'fa-hand-o-up': string
    'fa-hand-paper-o': string
    'fa-hand-peace-o': string
    'fa-hand-pointer-o': string
    'fa-hand-rock-o': string
    'fa-hand-scissors-o': string
    'fa-hand-spock-o': string
    'fa-hand-stop-o': string
    'fa-hashtag': string
    'fa-hdd-o': string
    'fa-header': string
    'fa-headphones': string
    'fa-heart': string
    'fa-heart-o': string
    'fa-heartbeat': string
    'fa-history': string
    'fa-home': string
    'fa-hospital-o': string
    'fa-hotel': string
    'fa-hourglass': string
    'fa-hourglass-1': string
    'fa-hourglass-2': string
    'fa-hourglass-3': string
    'fa-hourglass-end': string
    'fa-hourglass-half': string
    'fa-hourglass-o': string
    'fa-hourglass-start': string
    'fa-houzz': string
    'fa-html5': string
    'fa-i-cursor': string
    'fa-ils': string
    'fa-image': string
    'fa-inbox': string
    'fa-indent': string
    'fa-industry': string
    'fa-info': string
    'fa-info-circle': string
    'fa-inr': string
    'fa-instagram': string
    'fa-institution': string
    'fa-internet-explorer': string
    'fa-intersex': string
    'fa-ioxhost': string
    'fa-italic': string
    'fa-joomla': string
    'fa-jpy': string
    'fa-jsfiddle': string
    'fa-key': string
    'fa-keyboard-o': string
    'fa-krw': string
    'fa-language': string
    'fa-laptop': string
    'fa-lastfm': string
    'fa-lastfm-square': string
    'fa-leaf': string
    'fa-leanpub': string
    'fa-legal': string
    'fa-lemon-o': string
    'fa-level-down': string
    'fa-level-up': string
    'fa-life-bouy': string
    'fa-life-buoy': string
    'fa-life-ring': string
    'fa-life-saver': string
    'fa-lightbulb-o': string
    'fa-line-chart': string
    'fa-link': string
    'fa-linkedin': string
    'fa-linkedin-square': string
    'fa-linux': string
    'fa-list': string
    'fa-list-alt': string
    'fa-list-ol': string
    'fa-list-ul': string
    'fa-location-arrow': string
    'fa-lock': string
    'fa-long-arrow-down': string
    'fa-long-arrow-left': string
    'fa-long-arrow-right': string
    'fa-long-arrow-up': string
    'fa-magic': string
    'fa-magnet': string
    'fa-mail-forward': string
    'fa-mail-reply': string
    'fa-mail-reply-all': string
    'fa-male': string
    'fa-map': string
    'fa-map-marker': string
    'fa-map-o': string
    'fa-map-pin': string
    'fa-map-signs': string
    'fa-mars': string
    'fa-mars-double': string
    'fa-mars-stroke': string
    'fa-mars-stroke-h': string
    'fa-mars-stroke-v': string
    'fa-maxcdn': string
    'fa-meanpath': string
    'fa-medium': string
    'fa-medkit': string
    'fa-meh-o': string
    'fa-mercury': string
    'fa-microphone': string
    'fa-microphone-slash': string
    'fa-minus': string
    'fa-minus-circle': string
    'fa-minus-square': string
    'fa-minus-square-o': string
    'fa-mixcloud': string
    'fa-mobile': string
    'fa-mobile-phone': string
    'fa-modx': string
    'fa-money': string
    'fa-moon-o': string
    'fa-mortar-board': string
    'fa-motorcycle': string
    'fa-mouse-pointer': string
    'fa-music': string
    'fa-navicon': string
    'fa-neuter': string
    'fa-newspaper-o': string
    'fa-object-group': string
    'fa-object-ungroup': string
    'fa-odnoklassniki': string
    'fa-odnoklassniki-square': string
    'fa-opencart': string
    'fa-openid': string
    'fa-opera': string
    'fa-optin-monster': string
    'fa-outdent': string
    'fa-pagelines': string
    'fa-paint-brush': string
    'fa-paper-plane': string
    'fa-paper-plane-o': string
    'fa-paperclip': string
    'fa-paragraph': string
    'fa-paste': string
    'fa-pause': string
    'fa-pause-circle': string
    'fa-pause-circle-o': string
    'fa-paw': string
    'fa-paypal': string
    'fa-pencil': string
    'fa-pencil-square': string
    'fa-pencil-square-o': string
    'fa-percent': string
    'fa-phone': string
    'fa-phone-square': string
    'fa-photo': string
    'fa-picture-o': string
    'fa-pie-chart': string
    'fa-pied-piper': string
    'fa-pied-piper-alt': string
    'fa-pinterest': string
    'fa-pinterest-p': string
    'fa-pinterest-square': string
    'fa-plane': string
    'fa-play': string
    'fa-play-circle': string
    'fa-play-circle-o': string
    'fa-plug': string
    'fa-plus': string
    'fa-plus-circle': string
    'fa-plus-square': string
    'fa-plus-square-o': string
    'fa-power-off': string
    'fa-print': string
    'fa-product-hunt': string
    'fa-puzzle-piece': string
    'fa-qq': string
    'fa-qrcode': string
    'fa-question': string
    'fa-question-circle': string
    'fa-quote-left': string
    'fa-quote-right': string
    'fa-ra': string
    'fa-random': string
    'fa-rebel': string
    'fa-recycle': string
    'fa-reddit': string
    'fa-reddit-alien': string
    'fa-reddit-square': string
    'fa-refresh': string
    'fa-registered': string
    'fa-remove': string
    'fa-renren': string
    'fa-reorder': string
    'fa-repeat': string
    'fa-reply': string
    'fa-reply-all': string
    'fa-retweet': string
    'fa-rmb': string
    'fa-road': string
    'fa-rocket': string
    'fa-rotate-left': string
    'fa-rotate-right': string
    'fa-rouble': string
    'fa-rss': string
    'fa-rss-square': string
    'fa-rub': string
    'fa-ruble': string
    'fa-rupee': string
    'fa-safari': string
    'fa-save': string
    'fa-scissors': string
    'fa-scribd': string
    'fa-search': string
    'fa-search-minus': string
    'fa-search-plus': string
    'fa-sellsy': string
    'fa-send': string
    'fa-send-o': string
    'fa-server': string
    'fa-share': string
    'fa-share-alt': string
    'fa-share-alt-square': string
    'fa-share-square': string
    'fa-share-square-o': string
    'fa-shekel': string
    'fa-sheqel': string
    'fa-shield': string
    'fa-ship': string
    'fa-shirtsinbulk': string
    'fa-shopping-bag': string
    'fa-shopping-basket': string
    'fa-shopping-cart': string
    'fa-sign-in': string
    'fa-sign-out': string
    'fa-signal': string
    'fa-simplybuilt': string
    'fa-sitemap': string
    'fa-skyatlas': string
    'fa-skype': string
    'fa-slack': string
    'fa-sliders': string
    'fa-slideshare': string
    'fa-smile-o': string
    'fa-soccer-ball-o': string
    'fa-sort': string
    'fa-sort-alpha-asc': string
    'fa-sort-alpha-desc': string
    'fa-sort-amount-asc': string
    'fa-sort-amount-desc': string
    'fa-sort-asc': string
    'fa-sort-desc': string
    'fa-sort-down': string
    'fa-sort-numeric-asc': string
    'fa-sort-numeric-desc': string
    'fa-sort-up': string
    'fa-soundcloud': string
    'fa-space-shuttle': string
    'fa-spinner': string
    'fa-spoon': string
    'fa-spotify': string
    'fa-square': string
    'fa-square-o': string
    'fa-stack-exchange': string
    'fa-stack-overflow': string
    'fa-star': string
    'fa-star-half': string
    'fa-star-half-empty': string
    'fa-star-half-full': string
    'fa-star-half-o': string
    'fa-star-o': string
    'fa-steam': string
    'fa-steam-square': string
    'fa-step-backward': string
    'fa-step-forward': string
    'fa-stethoscope': string
    'fa-sticky-note': string
    'fa-sticky-note-o': string
    'fa-stop': string
    'fa-stop-circle': string
    'fa-stop-circle-o': string
    'fa-street-view': string
    'fa-strikethrough': string
    'fa-stumbleupon': string
    'fa-stumbleupon-circle': string
    'fa-subscript': string
    'fa-subway': string
    'fa-suitcase': string
    'fa-sun-o': string
    'fa-superscript': string
    'fa-support': string
    'fa-table': string
    'fa-tablet': string
    'fa-tachometer': string
    'fa-tag': string
    'fa-tags': string
    'fa-tasks': string
    'fa-taxi': string
    'fa-television': string
    'fa-tencent-weibo': string
    'fa-terminal': string
    'fa-text-height': string
    'fa-text-width': string
    'fa-th': string
    'fa-th-large': string
    'fa-th-list': string
    'fa-thumb-tack': string
    'fa-thumbs-down': string
    'fa-thumbs-o-down': string
    'fa-thumbs-o-up': string
    'fa-thumbs-up': string
    'fa-ticket': string
    'fa-times': string
    'fa-times-circle': string
    'fa-times-circle-o': string
    'fa-tint': string
    'fa-toggle-down': string
    'fa-toggle-left': string
    'fa-toggle-off': string
    'fa-toggle-on': string
    'fa-toggle-right': string
    'fa-toggle-up': string
    'fa-trademark': string
    'fa-train': string
    'fa-transgender': string
    'fa-transgender-alt': string
    'fa-trash': string
    'fa-trash-o': string
    'fa-tree': string
    'fa-trello': string
    'fa-tripadvisor': string
    'fa-trophy': string
    'fa-truck': string
    'fa-try': string
    'fa-tty': string
    'fa-tumblr': string
    'fa-tumblr-square': string
    'fa-turkish-lira': string
    'fa-tv': string
    'fa-twitch': string
    'fa-twitter': string
    'fa-twitter-square': string
    'fa-umbrella': string
    'fa-underline': string
    'fa-undo': string
    'fa-university': string
    'fa-unlink': string
    'fa-unlock': string
    'fa-unlock-alt': string
    'fa-unsorted': string
    'fa-upload': string
    'fa-usb': string
    'fa-usd': string
    'fa-user': string
    'fa-user-md': string
    'fa-user-plus': string
    'fa-user-secret': string
    'fa-user-times': string
    'fa-users': string
    'fa-venus': string
    'fa-venus-double': string
    'fa-venus-mars': string
    'fa-viacoin': string
    'fa-video-camera': string
    'fa-vimeo': string
    'fa-vimeo-square': string
    'fa-vine': string
    'fa-vk': string
    'fa-volume-down': string
    'fa-volume-off': string
    'fa-volume-up': string
    'fa-warning': string
    'fa-wechat': string
    'fa-weibo': string
    'fa-weixin': string
    'fa-whatsapp': string
    'fa-wheelchair': string
    'fa-wifi': string
    'fa-wikipedia-w': string
    'fa-windows': string
    'fa-won': string
    'fa-wordpress': string
    'fa-wrench': string
    'fa-xing': string
    'fa-xing-square': string
    'fa-y-combinator': string
    'fa-y-combinator-square': string
    'fa-yahoo': string
    'fa-yc': string
    'fa-yc-square': string
    'fa-yelp': string
    'fa-yen': string
    'fa-youtube': string
    'fa-youtube-play': string
    'fa-youtube-square': string
}


export interface MaterialColors {

    'red': string
    'red-1': string
    'red-2': string
    'red-3': string
    'red-4': string
    'red-5': string
    'red-6': string
    'red-7': string
    'red-8': string
    'red-9': string
    'red-10': string
    'red-11': string
    'red-12': string
    'red-13': string
    'red-14': string
    'pink': string
    'pink-1': string
    'pink-2': string
    'pink-3': string
    'pink-4': string
    'pink-5': string
    'pink-6': string
    'pink-7': string
    'pink-8': string
    'pink-9': string
    'pink-10': string
    'pink-11': string
    'pink-12': string
    'pink-13': string
    'pink-14': string
    'purple': string
    'purple-1': string
    'purple-2': string
    'purple-3': string
    'purple-4': string
    'purple-5': string
    'purple-6': string
    'purple-7': string
    'purple-8': string
    'purple-9': string
    'purple-10': string
    'purple-11': string
    'purple-12': string
    'purple-13': string
    'purple-14': string
    'deep-purple': string
    'deep-purple-1': string
    'deep-purple-2': string
    'deep-purple-3': string
    'deep-purple-4': string
    'deep-purple-5': string
    'deep-purple-6': string
    'deep-purple-7': string
    'deep-purple-8': string
    'deep-purple-9': string
    'deep-purple-10': string
    'deep-purple-11': string
    'deep-purple-12': string
    'deep-purple-13': string
    'deep-purple-14': string
    'indigo': string
    'indigo-1': string
    'indigo-2': string
    'indigo-3': string
    'indigo-4': string
    'indigo-5': string
    'indigo-6': string
    'indigo-7': string
    'indigo-8': string
    'indigo-9': string
    'indigo-10': string
    'indigo-11': string
    'indigo-12': string
    'indigo-13': string
    'indigo-14': string
    'blue': string
    'blue-1': string
    'blue-2': string
    'blue-3': string
    'blue-4': string
    'blue-5': string
    'blue-6': string
    'blue-7': string
    'blue-8': string
    'blue-9': string
    'blue-10': string
    'blue-11': string
    'blue-12': string
    'blue-13': string
    'blue-14': string
    'light-blue': string
    'light-blue-1': string
    'light-blue-2': string
    'light-blue-3': string
    'light-blue-4': string
    'light-blue-5': string
    'light-blue-6': string
    'light-blue-7': string
    'light-blue-8': string
    'light-blue-9': string
    'light-blue-10': string
    'light-blue-11': string
    'light-blue-12': string
    'light-blue-13': string
    'light-blue-14': string
    'cyan': string
    'cyan-1': string
    'cyan-2': string
    'cyan-3': string
    'cyan-4': string
    'cyan-5': string
    'cyan-6': string
    'cyan-7': string
    'cyan-8': string
    'cyan-9': string
    'cyan-10': string
    'cyan-11': string
    'cyan-12': string
    'cyan-13': string
    'cyan-14': string
    'teal': string
    'teal-1': string
    'teal-2': string
    'teal-3': string
    'teal-4': string
    'teal-5': string
    'teal-6': string
    'teal-7': string
    'teal-8': string
    'teal-9': string
    'teal-10': string
    'teal-11': string
    'teal-12': string
    'teal-13': string
    'teal-14': string
    'green': string
    'green-1': string
    'green-2': string
    'green-3': string
    'green-4': string
    'green-5': string
    'green-6': string
    'green-7': string
    'green-8': string
    'green-9': string
    'green-10': string
    'green-11': string
    'green-12': string
    'green-13': string
    'green-14': string
    'light-green': string
    'light-green-1': string
    'light-green-2': string
    'light-green-3': string
    'light-green-4': string
    'light-green-5': string
    'light-green-6': string
    'light-green-7': string
    'light-green-8': string
    'light-green-9': string
    'light-green-10': string
    'light-green-11': string
    'light-green-12': string
    'light-green-13': string
    'light-green-14': string
    'lime': string
    'lime-1': string
    'lime-2': string
    'lime-3': string
    'lime-4': string
    'lime-5': string
    'lime-6': string
    'lime-7': string
    'lime-8': string
    'lime-9': string
    'lime-10': string
    'lime-11': string
    'lime-12': string
    'lime-13': string
    'lime-14': string
    'yellow': string
    'yellow-1': string
    'yellow-2': string
    'yellow-3': string
    'yellow-4': string
    'yellow-5': string
    'yellow-6': string
    'yellow-7': string
    'yellow-8': string
    'yellow-9': string
    'yellow-10': string
    'yellow-11': string
    'yellow-12': string
    'yellow-13': string
    'yellow-14': string
    'amber': string
    'amber-1': string
    'amber-2': string
    'amber-3': string
    'amber-4': string
    'amber-5': string
    'amber-6': string
    'amber-7': string
    'amber-8': string
    'amber-9': string
    'amber-10': string
    'amber-11': string
    'amber-12': string
    'amber-13': string
    'amber-14': string
    'orange': string
    'orange-1': string
    'orange-2': string
    'orange-3': string
    'orange-4': string
    'orange-5': string
    'orange-6': string
    'orange-7': string
    'orange-8': string
    'orange-9': string
    'orange-10': string
    'orange-11': string
    'orange-12': string
    'orange-13': string
    'orange-14': string
    'deep-orange': string
    'deep-orange-1': string
    'deep-orange-2': string
    'deep-orange-3': string
    'deep-orange-4': string
    'deep-orange-5': string
    'deep-orange-6': string
    'deep-orange-7': string
    'deep-orange-8': string
    'deep-orange-9': string
    'deep-orange-10': string
    'deep-orange-11': string
    'deep-orange-12': string
    'deep-orange-13': string
    'deep-orange-14': string
    'brown': string
    'brown-1': string
    'brown-2': string
    'brown-3': string
    'brown-4': string
    'brown-5': string
    'brown-6': string
    'brown-7': string
    'brown-8': string
    'brown-9': string
    'brown-10': string
    'brown-11': string
    'brown-12': string
    'brown-13': string
    'brown-14': string
    'grey': string
    'grey-1': string
    'grey-2': string
    'grey-3': string
    'grey-4': string
    'grey-5': string
    'grey-6': string
    'grey-7': string
    'grey-8': string
    'grey-9': string
    'grey-10': string
    'grey-11': string
    'grey-12': string
    'grey-13': string
    'grey-14': string
    'blue-grey': string
    'blue-grey-1': string
    'blue-grey-2': string
    'blue-grey-3': string
    'blue-grey-4': string
    'blue-grey-5': string
    'blue-grey-6': string
    'blue-grey-7': string
    'blue-grey-8': string
    'blue-grey-9': string
    'blue-grey-10': string
    'blue-grey-11': string
    'blue-grey-12': string
    'blue-grey-13': string
    'blue-grey-14': string
}

export type MaterialColorName = keyof MaterialColors
export type AntColorName = keyof AntColors

export interface AntColors {
    'blue-1': string
    'blue-2': string
    'blue-3': string
    'blue-4': string
    'blue-5': string
    'blue-6': string
    'blue-7': string
    'blue-8': string
    'blue-9': string
    'blue-10': string

    'purple-1': string
    'purple-2': string
    'purple-3': string
    'purple-4': string
    'purple-5': string
    'purple-6': string
    'purple-7': string
    'purple-8': string
    'purple-9': string
    'purple-10': string

    'cyan-1': string
    'cyan-2': string
    'cyan-3': string
    'cyan-4': string
    'cyan-5': string
    'cyan-6': string
    'cyan-7': string
    'cyan-8': string
    'cyan-9': string
    'cyan-10': string

    'green-1': string
    'green-2': string
    'green-3': string
    'green-4': string
    'green-5': string
    'green-6': string
    'green-7': string
    'green-8': string
    'green-9': string
    'green-10': string

    'magenta-1': string
    'magenta-2': string
    'magenta-3': string
    'magenta-4': string
    'magenta-5': string
    'magenta-6': string
    'magenta-7': string
    'magenta-8': string
    'magenta-9': string
    'magenta-10': string

// alias of magenta
    'pink-1': string
    'pink-2': string
    'pink-3': string
    'pink-4': string
    'pink-5': string
    'pink-6': string
    'pink-7': string
    'pink-8': string
    'pink-9': string
    'pink-10': string

    'red-1': string
    'red-2': string
    'red-3': string
    'red-4': string
    'red-5': string
    'red-6': string
    'red-7': string
    'red-8': string
    'red-9': string
    'red-10': string

    'orange-1': string
    'orange-2': string
    'orange-3': string
    'orange-4': string
    'orange-5': string
    'orange-6': string
    'orange-7': string
    'orange-8': string
    'orange-9': string
    'orange-10': string

    'yellow-1': string
    'yellow-2': string
    'yellow-3': string
    'yellow-4': string
    'yellow-5': string
    'yellow-6': string
    'yellow-7': string
    'yellow-8': string
    'yellow-9': string
    'yellow-10': string

    'volcano-1': string
    'volcano-2': string
    'volcano-3': string
    'volcano-4': string
    'volcano-5': string
    'volcano-6': string
    'volcano-7': string
    'volcano-8': string
    'volcano-9': string
    'volcano-10': string

    'geekblue-1': string
    'geekblue-2': string
    'geekblue-3': string
    'geekblue-4': string
    'geekblue-5': string
    'geekblue-6': string
    'geekblue-7': string
    'geekblue-8': string
    'geekblue-9': string
    'geekblue-10': string

    'lime-1': string
    'lime-2': string
    'lime-3': string
    'lime-4': string
    'lime-5': string
    'lime-6': string
    'lime-7': string
    'lime-8': string
    'lime-9': string
    'lime-10': string

    'gold-1': string
    'gold-2': string
    'gold-3': string
    'gold-4': string
    'gold-5': string
    'gold-6': string
    'gold-7': string
    'gold-8': string
    'gold-9': string
    'gold-10': string

}

